meta_product_name: "Alerta Greves"
meta_title: "Alerta Greves - All strikes in one place"
meta_description: "Everyone got affected by strikes at some point... With Alerta Greves we make sure you got all relevant news about strikes"
meta_image: "logo-7.svg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards